name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Устанавливаем Node.js для инструментов минификации
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Или другая версия

      # 3. Устанавливаем глобально необходимые инструменты
      - name: Install dependencies
        run: |
          npm install -g html-minifier terser clean-css-cli svgo
          sudo apt-get update && sudo apt-get install -y libxml2-utils

      # 4. Удаляем все файлы .cgm
      #- name: Remove all .cgm files
      #  continue-on-error: true
      #  run: find . -name '*.cgm' -type f -delete

      # 5. Минификация HTML/HTM
      - name: Minify HTML/HTM files
        continue-on-error: true
        run: |
          set -e
          echo "Minifying HTML/HTM files..."
          # ищем файлы *.html и *.htm
          for file in $(find . -type f \( -name '*.html' -o -name '*.htm' \)); do
            echo "  -> $file"
            html-minifier \
              --collapse-whitespace \
              --remove-comments \
              --remove-optional-tags \
              --minify-js \
              --minify-css \
              -o "$file" "$file"
          done

      # 6. Минификация CSS
      - name: Minify CSS files
        continue-on-error: true
        run: |
          set -e
          echo "Minifying CSS files..."
          for file in $(find . -type f -name '*.css'); do
            echo "  -> $file"
            cleancss -o "$file" "$file"
          done

      # 7. Минификация JS
      - name: Minify JS files
        continue-on-error: true
        run: |
          set -e
          echo "Minifying JS files..."
          for file in $(find . -type f -name '*.js'); do
            echo "  -> $file"
            terser --compress --mangle -o "$file" -- "$file"
          done

      # 8. Минификация XML
      - name: Minify XML files (real single-line)
        continue-on-error: true
        run: |
          echo "Minifying XML files..."
          for file in $(find . -type f -name '*.xml'); do
            echo "  -> $file"
            xmllint --noblanks "$file" | tr -d '\n' > tmpfile && mv tmpfile "$file"
          done
    
      # # 9. Минификация SVG
      # - name: Minify SVG files
      #   continue-on-error: true
      #   run: |
      #     set -e
      #     echo "Minifying SVG files..."
      #     for file in $(find . -type f -name '*.svg'); do
      #       echo "  -> $file"
      #       svgo -i "$file" -o "$file"
      #     done

      # 10. Деплой на gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .  # Публикуем всё из корня
